name: 'Get Bus Type'
description: 'Get Bus Type'
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Extract Info from IP Yaml File
      uses: mikefarah/yq@master
      id: get_bus_info
      with:
        cmd: yq '.info.bus.[]' './${{ github.event.repository.name }}.yaml'
    - name: Map to Make options
      shell: bash
      run: |
        buses=(${{ steps.get_bus_info.outputs.result }})
        output=""
        for bus in "${buses[@]}"
        do
          if [[ "$bus" == "generic" ]]; then
            output="WISHBONE ABP AHB $output"
          elif [[ "$bus" == "ABP" ]]; then
            output="ABP $output"
          elif [[ "$bus" == "AHBL" ]]; then
            output="AHB $output"
          elif [[ "$bus" == "WB" ]]; then
            output="WISHBONE $output"
          else
            echo "Unknown bus type $bus"
            exit 1
          fi
        done
