- name: EF_GPIO8
  url: https://github.com/efabless/EF_GPIO8.git
  tests:
    - gpio8_all_out_test gpio8_all_in_test
  bus:
    - APB
    - AHB
    - WISHBONE
- name: EF_UART
  url: https://github.com/efabless/EF_UART.git
  tests:
    - TX_StressTest LoopbackTest PrescalarStressTest 
    - LengthParityTXStressTest LengthParityRXStressTest WriteReadRegsTest
  bus:
    - APB
    - AHB
    - WISHBONE
- name: EF_TMR32
  url: https://github.com/efabless/EF_TMR32.git
  tests:
    - pwm_actions_test time_vary_test 
    - pwm_pr_test
  bus:
    - APB
    - AHB
    - WISHBONE
- name: EF_QSPI_XIP_CTRL
  url: https://github.com/efabless/EF_QSPI_XIP_CTRL.git
  tests:
    - flashReadTest flashResetTest flashRdWrTest
  bus:
    - AHB
- name: OL-DFFRAM
  url: https://github.com/efabless/OL-DFFRAM.git
  tests:
    - dffram_wr_rd_test dffram_corners_test
  bus:
    - AHB
- name: EF_SPI
  url: https://github.com/efabless/EF_SPI.git
  tests:
    - MOSI_stress_test MISO_stress_test 
    - MISO_MOSI_test
  bus:
    - APB
    - AHB
    - WISHBONE
- name: EF_I2C
  url: https://github.com/efabless/EF_I2C.git
  tests:
    - i2c_write_read_test WriteReadRegsTest
  bus:
    - APB
    - WISHBONE
- name: EF_I2S
  url: https://github.com/efabless/EF_I2S.git
  tests:
    - i2s_stereo_test WriteReadRegsTest
    - i2s_averaging_test 
  bus:
    - APB
    - WISHBONE
    - AHB
- name: EF_PSRAM_CTRL_V2
  url: https://github.com/efabless/EF_PSRAM_CTRL_V2.git
  tests:
    - psram_spi_test psram_sqi_test
  bus:
    - AHB