name: 'Install PDK'
description: 'Install PDK using volare. Uses github actions cache'
runs:
  using: "composite"
  steps:
    - name: Cache PDK
      id: cache-pdk
      uses: actions/cache/restore@v4
      with:
        path: ${{env.PDK_ROOT}}
        key: pdk-${{env.OPEN_PDKS_COMMIT}}
        enableCrossOsArchive: "true"
    - name: Download PDK
      shell: bash
      if: ${{ steps.cache-pdk.outputs.cache-hit != 'true' }} 
      run: |
        mkdir -p ${{ env.PDK_ROOT }}
        pip install volare
        volare enable ${{ env.OPEN_PDKS_COMMIT }}
    - name: Save PDK Cache
      if: ${{ steps.cache-pdk.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ${{env.PDK_ROOT}}
        key: pdk-${{env.OPEN_PDKS_COMMIT}}
