name: 'Run Test'
description: 'Clones and Runs a test'
inputs:
  url:
    description: 'Repo URL'
    required: true
  test-names:
    description: 'Test Names'
    required: true
  name:
    description: 'IP Name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone IP
      shell: bash
      run: git clone ${{ inputs.url }} $HOME/work/${{ inputs.name }}
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Run Test
      shell: bash
      run: |
        echo $(pwd)
        ls
        cp -r $(pwd) $HOME/work/${{ inputs.name }}/verify/uvm-python/
        cd $HOME/work/${{ inputs.name }}/verify/uvm-python
        echo $(pwd)
        ls
        for test in ${{ inputs.test-names }}; do
          echo "Running Test $test"
          make run_$test
        done



