name: 'Run Test'
description: 'Clones and Runs a test'
inputs:
  url:
    description: 'Repo URL'
    required: true
  test-names:
    description: 'Test Names'
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone IP
      shell: bash
      run: git clone ${{ inputs.url }}
    - name: Run Test
      shell: bash
      run: |
        for test in ${{ inputs.test-names }}; do
          echo "Running Test $test"
        done


