name: 'Run Test'
description: 'Clones and Runs a test'
inputs:
  url:  # id of input
    description: 'repo url'
    required: true
  tests:
    description: 'Test Names'
runs:
  using: "composite"
  steps:
    - name: Clone IP
      run: git clone ${{ inputs.url }}
    - name: Run Test
      run: |
        for test in ${{ inputs.tests }}; do
          echo "Running Test $test"
        done


