name: 'Run Test'
description: 'Clones and Runs a test'
inputs:
  url:
    description: 'Repo URL'
    required: true
  test-names:
    description: 'Test Names'
    required: true
  name:
    description: 'IP Name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone IP
      shell: bash
      run: git clone ${{ inputs.url }} $HOME/work/${{ inputs.name }}
    - name: Copy Dirs
      shell: bash
      run: cp -r $HOME/work/EF_UVM/EF_UVM $HOME/work/${{ inputs.name }}/verify/uvm-python/
    - name: Download Docker Image
      shell: bash
      run: docker pull efabless/dv:cocotb
    - name: Run Test
      shell: bash
      run: |
        cd $HOME/work/${{ inputs.name }}/verify/uvm-python
        for test in ${{ inputs.test-names }}; do
          echo "Running Test $test"
          ls EF_UVM/Makefile.test
          make run_$test
        done



