name: 'Setup OpenLane'
description: 'Install Nix and Setup OpenLane cachix'
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: "true"
        remove-android: "true"
        remove-haskell: "true"
        remove-codeql: "true"
        remove-docker-images: "true"
        root-reserve-mb: 20480
    
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-substituters = https://openlane.cachix.org
          extra-trusted-public-keys = openlane.cachix.org-1:qqdwh+QMNGmZAuyeQJTH9ErW57OWSvdtuwfBKdS254E=
    - name: Run OpenLane Smoke Test
      shell: bash
      run: nix run github:efabless/openlane2 -- --smoke-test
