name: Test IPs
on: [push]
jobs:
  Prepare-Tests-Matrix:
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{steps.set-tests-matrix.outputs.tests-matrix}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Tests Matrix
        id: set-tests-matrix
        run: echo "tests-matrix=$(python3 ./.github/scripts/get_tests_matrix.py)" >> "$GITHUB_OUTPUT"

  Test:
    runs-on: ubuntu-latest
    needs: [Prepare-Tests-Matrix]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Matrix
        run: ${{ needs.Prepare-Tests-Matrix.outputs.tests-matrix }}

