name: Test IPs
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.test.outputs.test }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Tests Matrix
        id: test
        run: echo "test=$(python3 ./.github/scripts/get_tests_matrix.py)" >> "$GITHUB_OUTPUT"

  Test1:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Matrix
        run: ${{ needs.test.outputs.test }}

