name: Test IPs
on: [push]
jobs:
  Prepare-Tests-Matrix:
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{steps.set-test-matrix.outputs.tests-matrix}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Tests Matrix
        id: set-tests-matrix
        run: echo "test-matrix=$(python3 ./.github/scripts/get_tests_matrix.py)" >> "$GITHUB_OUTPUT"

  Test:
    runs-on: ubuntu-latest
    needs: [Prepare-Tests-Matrix]
    name: IP-${{ matrix.tests.name }} Test ${{ matrix.tests.test}}
    strategy:
      matrix: ${{ fromJSON(needs.Prepare-Tests-Matrix.outputs.test-matrix) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

