name: Test IPs
on: [push]
jobs:
  prepare-tests-matrix:
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{steps.set-test-matrix.outputs.tests-matrix}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Tests Matrix
        id: set-tests-matrix
        run: |
          python3 ./.github/scripts/get_tests_matrix.py
          echo "test-matrix=$(python3 ./.github/scripts/get_tests_matrix.py)" >> "$GITHUB_OUTPUT"

  Test:
    runs-on: ubuntu-latest
    needs: [prepare-tests-matrix]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Matrix
        run: echo ${{ needs.prepare-tests-matrix.outputs.test-matrix }}

