name: 'Run IP'
on:
  workflow_call:
    inputs:
      url:
        description: 'IP Repo URL'
        required: true
        type: string
      test-names:
        description: 'Test Names'
        required: true
        type: string
      name:
        description: 'IP Name'
        required: true
        type: string
jobs:
  Prepare-Tests-Matrix:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.set-tests-matrix.outputs.tests }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Tests Matrix
        id: set-tests-matrix
        run: echo "tests=$(python3 ./.github/scripts/get_tests_matrix.py ${{ inputs.test-names }})" >> "$GITHUB_OUTPUT"

  Run-IP:
    needs: [Prepare-Tests-Matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.Prepare-Tests-Matrix.outputs.tests) }}
    name: ${{ matrix.tests.test }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup OpenLane
        uses: ./.github/actions/setup-openlane-nix
      - name: Clone IP
        shell: bash
        run: git clone ${{ inputs.url }} /home/runner/work/${{ inputs.name }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Copy EF_UVM ot verify/uvm-python (workaround)
        shell: bash
        run: cp -r $(pwd) /home/runner/work/${{ inputs.name }}/verify/uvm-python/
      - name: Install Docker Image
        run: docker pull efabless/dv:cocotb 
      - name: Run Test
        shell: bash
        working-directory: /home/runner/work/${{ inputs.name }}/verify/uvm-python
        run: |
          for test in ${{ matrix.tests.test }}; do
            echo "Running Test $test"
            make run_$test SIM_TAG=RTL
            make run_gl_$test SIM_TAG=GL
          done 
      - name: Tar Test Logs
        shell: bash
        working-directory: /home/runner/work/${{ inputs.name }}/verify/uvm-python
        run: tar -czf sim.tar.gz sim
      - name: Check Test Results
        shell: bash
        working-directory: /home/runner/work/${{ inputs.name }}/verify/uvm-python
        run: |
          passed_count=$(find sim/* -type f -name 'passed' | wc -l)
          failed_count=$(find sim/* -type f -name 'failed' | wc -l)
          unknown_count=$(find sim/* -type f -name 'unknown' | wc -l)

          echo "Passed: $passed_count"
          echo "Failed: $failed_count"
          echo "Unknown: $unknown_count"

          if [ "$passed_count" -eq 0 ]; then
            echo "Error: No passed test results found"
            exit 1
          elif [ "$failed_count" -ne 0 ] || [ "$unknown_count" -ne 0 ]; then
            echo "Error: There are failed or unknown test results"
            exit 1
          else
            echo "All tests passed successfully"
          fi
      - name: Save IP Commit Hash
        if: always()
        shell: bash
        working-directory: /home/runner/work/${{ inputs.name }}/verify/uvm-python
        run: git rev-parse --verify HEAD > /tmp/ip-commit-hash.txt
      - name: Save EF_UVM Commit Hash
        if: always()
        shell: bash
        run: git rev-parse --verify HEAD > /tmp/EF_UVM-commit-hash.txt
      - name: Upload Commit Hashes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.name }}-${{ matrix.tests.test }}-commit-hashes
          path: /tmp/*hash.txt
      - name: Upload Logs and Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.name }}-${{ matrix.tests.test }}-sim
          path: /home/runner/work/${{ inputs.name }}/verify/uvm-python/*.tar.gz




